/**
 * convert-fonts.js
 * Run from your project root: node convert-fonts.js
 *
 * Before running:
 * 1. Download EB Garamond from https://fonts.google.com/specimen/EB+Garamond
 * 2. Unzip — you'll find the TTF files inside the static/ folder
 * 3. Copy these 4 files into a folder called /fonts at your project root:
 *    - EBGaramond-Regular.ttf
 *    - EBGaramond-Italic.ttf
 *    - EBGaramond-Bold.ttf
 *    - EBGaramond-BoldItalic.ttf
 * 4. Run: node convert-fonts.js
 * 5. Move the generated files from /fonts into /src/fonts/
 */

const fs = require('fs')
const path = require('path')

const fonts = [
  { file: 'EBGaramond-Regular.ttf',     export: 'EBGaramondRegular',     name: 'EBGaramond-Regular' },
  { file: 'EBGaramond-Italic.ttf',      export: 'EBGaramondItalic',      name: 'EBGaramond-Italic' },
  { file: 'EBGaramond-Bold.ttf',        export: 'EBGaramondBold',        name: 'EBGaramond-Bold' },
  { file: 'EBGaramond-BoldItalic.ttf',  export: 'EBGaramondBoldItalic',  name: 'EBGaramond-BoldItalic' },
]

const inputDir  = path.join(__dirname, 'fonts')
const outputDir = path.join(__dirname, 'fonts')

fonts.forEach(({ file, export: exportName, name }) => {
  const inputPath  = path.join(inputDir, file)
  const outputPath = path.join(outputDir, `${name}.ts`)

  if (!fs.existsSync(inputPath)) {
    console.error(`❌  Not found: ${inputPath}`)
    console.error(`   Make sure ${file} is in the /fonts folder`)
    return
  }

  const base64 = fs.readFileSync(inputPath).toString('base64')
  const content = `// Auto-generated by convert-fonts.js — do not edit manually\nexport const ${exportName} = '${base64}'\n`

  fs.writeFileSync(outputPath, content)
  const kb = Math.round(base64.length / 1024)
  console.log(`✅  ${file} → ${name}.ts (${kb}KB)`)
})

console.log('\nDone! Move the generated .ts files into /src/fonts/')